### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by samuelick8** [bsung1/brandon-website#3]
Technical Suggestions
1. On homepage, increase the font size of the navigation bar and text to the right and left of your picture. I had to squint a little to read it all.
2.  Space out your navigation bar a little more by adding padding. Your homepage looks very slick, and a few usability changes will make it look like a professionally done homepage.
3. Change the color when clicked on the navigation bar, currently it turns purple and is hard to see with the black background.

Content Suggestions
1. Add some descriptions to the rare clothing images, I'd love to learn more about them.
2. There is probably really cool things you can do with JavaScript on your homepage. For example enlarging the text when hovered over.

**Comment by bsung1** [comment]
Got it thanks!
